default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['BD_LOCAL_USER'] %>
  password: <%= ENV['BD_LOCAL_PASSWORD'] %>

development:
  <<: *default
  database: curso_development
  port: 5432
  host: localhost

test:
  <<: *default
  database: curso_test
  port: 5432
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
